In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('origin\\final_df.csv')

In [16]:
df

,id,text,label,dataset_type
0,0,Dừa lắm :)),0,train
1,1,Bấp bênh vl thế,1,train
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train
...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test

In [17]:
df.drop_duplicates(subset=['text'], keep='first', inplace=True)

In [18]:
df

,id,text,label,dataset_type
0,0,Dừa lắm :)),0,train
1,1,Bấp bênh vl thế,1,train
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train
...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test

In [19]:
df.dropna(inplace=True, how= 'any')

In [20]:
df

,id,text,label,dataset_type
0,0,Dừa lắm :)),0,train
1,1,Bấp bênh vl thế,1,train
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train
...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test

In [21]:
df['less_than_15'] = df['text'].apply(lambda x: len(x) < 15)

In [22]:
df

,id,text,label,dataset_type,less_than_15
0,0,Dừa lắm :)),0,train,True
1,1,Bấp bênh vl thế,1,train,False
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train,False
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train,False
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train,False
...,...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test,False
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test,False
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test,False
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test,False
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test,False

In [23]:
df.drop(df[df['less_than_15'] == True].index, inplace=True)

In [24]:
df

,id,text,label,dataset_type,less_than_15
1,1,Bấp bênh vl thế,1,train,False
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train,False
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train,False
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train,False
5,5,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...,1,train,False
...,...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test,False
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test,False
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test,False
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test,False
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test,False

In [25]:
texts = df['text'].tolist()
# cnt = 0
for index, s in enumerate(texts):
    check_text = s[3: 33]
    if check_text is None: continue
    for j in range(index+1, len(texts)):
        try:
            if check_text in texts[j]:
                texts[index] = None
                # print(f'check: {s}')
                # print(f'duplicate at {texts[j]}')
                # print('')
        except:
            print(f'start error: {s}')
            print(f'end error: {texts[j]}')
    # cnt += 1
    # if cnt == 1000:
    #     break

In [26]:
df['deduped_text'] = texts

In [27]:
df

,id,text,label,dataset_type,less_than_15,deduped_text
1,1,Bấp bênh vl thế,1,train,False,Bấp bênh vl thế
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train,False,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train,False,Thấy chán ad page này kiến thức thì nông cản c...
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train,False,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa
5,5,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...,1,train,False,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...
...,...,...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test,False,"trong trường hợp này, theo ls. khanh, bà hằng..."
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test,False,bà cũng không ít lần chỉ trích nặng nề những ...
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test,False,“bà nguyễn phương hằng có nhiều biểu hiện đã ...
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test,False,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test,False,".. trước khi bị bắt, bà nguyễn phương hằng đã ..."

In [28]:
dedup = df.loc[df['deduped_text'].isna()]

In [29]:
dedup

,id,text,label,dataset_type,less_than_15,deduped_text
60,60,cho xin video vs,0,train,False,None
100,100,con nay mat dai,1,train,False,None
156,156,Dm quảng cáo :)),1,train,False,None
198,198,Non quá thầy ơi,1,train,False,None
388,388,T có súng đây này,0,train,False,None
...,...,...,...,...,...,...
72609,72609,ủy ban khuyến nghị nhà nước việt nam tiếp tục...,1,test,False,None
72654,72654,theo trung tâm dự báo khí tượng thủy văn quốc ...,0,test,False,None
72891,72891,"bs.ckii tạ phương dung, phó giám đốc trung tâm...",0,test,False,None
73206,73206,---------------------------------- phát sóng ...,0,test,False,None
75046,75046,cơ quan cảnh sát điều tra bộ công an đã hoàn t...,0,test,False,None

In [32]:
dedup.reset_index(drop=True, inplace=True)

In [33]:
def analysis_result(df: pd.DataFrame, start):
    for i in range(start, start+10):
        print(df.loc[i, 'text'])
        # print(df.loc[i, ['label', 'predict_proba', 'predict_label']])
        print('-----------------------------')

In [34]:
analysis_result(dedup, 600)

 chia sẻ của patricia mayerhofer trở thành chủ đề được bàn tán sôi nổi trên mạng xã hội. bên dưới bài viết, rất nhiều bình luận khác của khách nước ngoài nói rằng họ cũng có những trải nghiệm tương tự khi đến vịnh hạ long. theo: dân trí
-----------------------------
bài học về lưu giữ và phát huy văn hóa dân tộc cho trẻ nhỏ giữ gìn và phát huy di sản văn hóa dân tộc luôn là một bài học khó, cần nhiều thời gian và với các bạn nhỏ lại càng khó hơn. để các bạn nhỏ có thể yêu say văn hóa truyền thống, điểm bắt đầu vẫn là trao cho các em cơ hội tiếp xúc, được học và được hiểu. cùng vì tầm vóc việt bắt đầu bài học bằng việc nỗ lực truyền lửa, bảo tồn di sản văn hóa cồng chiêng trên cao nguyên đại ngàn ---------------------------------- phát sóng 20h05 hằng ngày trên kênh vtv1 xem thêm tại youtube: vì tầm vóc việt channel
-----------------------------
câu chuyện lớn ở ao hạ long (phần 1) 06/11/2023 nguyễn huy cường 6-11-2023 ảnh: báo tiền phong báo tiền phong đã nổ phát súng muộn mằn vĩ đại, báo hiệu một sự kiện có tên “hòn non bộ hạ long”. lẽ ra các báo phải có bài này từ ngày họ đổ những ngàn xe đất đầu tiên, nhưng nay mới có, thôi, chậm cũng hơn không. có rất nhiều vấn đề xung quanh câu chuyện này
-----------------------------
tổ chức christian solidarity worldwide (đoàn kết thiên chúa giáo toàn cầu) lên tiếng về việc bộ công an gọi 2 tổ chức người thượng vì công lý (msfj) và nhóm hỗ trợ người thượng (msgi) là tổ chức khủng bố. chủ tịch sáng lập csw mervyn thomas nói: "chính phủ việt nam đang gây nguy hiểm đến tính mạng những người đấu tranh nhân quyền khi nêu tên và chia sẻ địa chỉ của họ trên các phương tiện truyền thông nhà nước, gây ra lo ngại an ninh trực tiếp và rõ ràng nhằm để bịt miệng, sách nhiễu, và đe dọa. chính phủ việt nam là một nhà nước độc tài hoang tưởng là thế giới sẽ biết mức độ thực sự cách họ kiểm soát và đàn áp các tôn giáo và sắc tộc thiểu số, và đây là bằng chứng nữa cho thấy họ ngang nhiên đàn áp xuyên quốc gia với các nhà hoạt động chỉ đơn giản đang thực hiện quyền tự do ngôn luận của mình
-----------------------------
song song với chương trình của hội nghị thượng đỉnh về tự do tôn giáo quốc tế 2024, bắt đầu ngày hôm nay, bpsos tổ chức sinh hoạt bên lề, đặc biệt là chuỗi hội luận về tự do tôn giáo và niềm tin ở việt nam, bao gồm chủ đề các tổ chức tôn giáo bị nhà nước bị kiểm soát. các hội luận sẽ được livestream ở đây, từ 8g30 tối giờ việt nam. xin mời quý vị đón xem
-----------------------------
viện nghiên cứu hòa bình quốc tế stockholm (sipri) hôm nay, 11/03/2024, cho biết nhập khẩu vũ khí của châu âu đã tăng gần gấp đôi trong 5 năm qua, một phần do chiến tranh ukraina, trong khi xuất khẩu vũ khí của nga giảm một nửa.
-----------------------------
"tổ chức theo dõi nhân quyền (hrw) hôm 11/1 nói rằng chính phủ việt nam trong năm 2023 đã đàn áp trên diện rộng các quyền dân sự và chính trị căn bản, đồng thời trừng phạt khắc nghiệt những người thách thức sự độc tôn quyền lực của đảng cộng sản việt nam. hrw đưa ra đánh giá trên trong báo cáo tổng kết toàn cầu 2024 về tình hình nhân quyền trên thế giới, trong đó có phần tổng kết tình hình tại việt nam. [
-----------------------------
 mời quý vị theo dõi video tóm tắt về sự việc trên qua phần phỏng vấn của đài radio saigon dallas với ts. nguyễn đình thắng.
-----------------------------
 chương trình do đài truyền hình việt nam kết hợp cùng hệ thống bvđk tâm anh tổ chức. phát sóng trực tiếp trên báo điện tử thanhnien.vn, website tamanhhospital
-----------------------------
vn. livestream trên các fanpage: vtv24 - trung tâm tin tức, vtv8 - đài truyền hình việt nam, báo điện tử vnexpress.net, báo thanh niên, bệnh viện đa khoa tâm anh, cơ xương khớp tâm anh, tt chấn thương chỉnh hình - bvđk tâm anh; kênh youtube bệnh viện đa khoa tâm anh, youtube báo thanh niên, youtube chấn thương chỉnh hình tâm anh
-----------------------------

In [35]:
df.dropna(inplace=True, how= 'any')

In [36]:
df

,id,text,label,dataset_type,less_than_15,deduped_text
1,1,Bấp bênh vl thế,1,train,False,Bấp bênh vl thế
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train,False,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train,False,Thấy chán ad page này kiến thức thì nông cản c...
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train,False,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa
5,5,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...,1,train,False,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...
...,...,...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test,False,"trong trường hợp này, theo ls. khanh, bà hằng..."
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test,False,bà cũng không ít lần chỉ trích nặng nề những ...
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test,False,“bà nguyễn phương hằng có nhiều biểu hiện đã ...
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test,False,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test,False,".. trước khi bị bắt, bà nguyễn phương hằng đã ..."

In [37]:
df.drop(columns=['less_than_15', 'deduped_text'], inplace=True)

In [38]:
df

,id,text,label,dataset_type
1,1,Bấp bênh vl thế,1,train
2,2,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train
3,3,Thấy chán ad page này kiến thức thì nông cản c...,1,train
4,4,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train
5,5,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...,1,train
...,...,...,...,...
76122,76122,"trong trường hợp này, theo ls. khanh, bà hằng...",0,test
76123,76123,bà cũng không ít lần chỉ trích nặng nề những ...,0,test
76124,76124,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test
76125,76125,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test
76126,76126,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test

In [46]:
df.drop(columns='id', inplace= True)

In [47]:
df.reset_index(drop=False, inplace=True)

In [49]:
df.drop(columns='index', inplace=True)

In [52]:
df.reset_index(inplace=True)

In [54]:
df.rename(columns={'index': 'id'}, inplace=True)

In [55]:
df

,id,text,label,dataset_type
0,0,Bấp bênh vl thế,1,train
1,1,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train
2,2,Thấy chán ad page này kiến thức thì nông cản c...,1,train
3,3,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train
4,4,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...,1,train
...,...,...,...,...
46002,46002,"trong trường hợp này, theo ls. khanh, bà hằng...",1,test
46003,46003,bà cũng không ít lần chỉ trích nặng nề những ...,0,test
46004,46004,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test
46005,46005,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test
46006,46006,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test

In [56]:
df.to_csv('origin/all_dedup.csv', index=False)

In [57]:
train_data = df.loc[df['dataset_type'] == 'train']

In [58]:
test_data = df.loc[df['dataset_type'] != 'train']

In [61]:
average_len = len(df) // 2

In [59]:
train_data

,id,text,label,dataset_type
0,0,Bấp bênh vl thế,1,train
1,1,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train
2,2,Thấy chán ad page này kiến thức thì nông cản c...,1,train
3,3,Giang Giang Đỗ Thị Ngọc Hà trend mới kìa kìa,0,train
4,4,đcm 😒 sau có con cho hút cỏ chữa bệnh chứ đéo ...,1,train
...,...,...,...,...
44129,44129,nh cho không ăn được luôn. cảnh báo: video có ...,0,train
44130,44130,dịp hiếm ngắm nhìn chim uyên ương khi du xuân ...,0,train
44131,44131,việt nam: rò rỉ tài liệu đảng cộng sản cảnh bá...,1,train
44132,44132,điều không thay đổi là sự kìm kẹp sắt đá của ...,1,train
44133,44133,được bộ chính trị việt nam ban hành vào tháng...,1,train

In [62]:
data1 = train_data.sample(n=average_len, random_state=42)

In [64]:
data1

,id,text,label,dataset_type
26180,26180,Chuyện ly kỳ..!,0,train
11069,11069,Nhìn đội hình chắc ai cũng bt thầy ba yếu nhất,0,train
28019,28019,Há miệng chờ trê.,0,train
4384,4384,Định mệnh rùi nay là mùng BA,0,train
31953,31953,Chính mái tóc ấy mà lớp trưởng ghét tôi. Giờ c...,0,train
...,...,...,...,...
18415,18415,trong 3 tháng tới nếu giao thông ko có chuyển ...,0,train
2047,2047,Vcl lag nó thấy thì nó chụp liền chứ vừa thấy ...,1,train
104,104,Tao mà bắt gặp thg nào là tao bêu rếu nó từ đầ...,1,train
36967,36967,mạng * 12) người đứng thứ hai trong tứ đại ác ...,1,train
20185,20185,Rất buồn.....ngủ,0,train

In [63]:
data2 = train_data.drop(data1.index)

In [65]:
data2

,id,text,label,dataset_type
1,1,Chắc cũng biết ko tồn tại đc bao lâu nữa nên c...,1,train
9,9,Emma Nguyen vậy mà ca ngợi bên kia lắm... Về l...,1,train
11,11,Nhung Pham Ai chê nghèo ngta có tiền đi nước n...,1,train
13,13,Ủa bê đê có lol hả ta ??😂😂😂,1,train
16,16,Làm thêm chục củ mở hòm csgo anh êi :V,0,train
...,...,...,...,...
44119,44119,"nhờ vào bàn tay đảm đang, khéo léo cộng thêm ...",0,train
44122,44122,"Chính quyền này, nó không phải là cơ quan của...",1,train
44124,44124,"Đừng để cho những kẻ độc tài, những kẻ không ...",1,train
44125,44125,ukraine từ chối trung quốc viện trợ trước sự p...,0,train
44133,44133,được bộ chính trị việt nam ban hành vào tháng...,1,train

In [60]:
test_data

,id,text,label,dataset_type
7470,7470,"Cs cha , Cs con , Rận cha, Rận con ...ai đúng ...",1,dev
7471,7471,Long Duy Đào cái tội ớ,0,dev
7472,7472,Nói gì tào lao kg,1,dev
7473,7473,Chả làm gì cũng có fan cứng =)),0,dev
7474,7474,Sao lại cứ đến nụ cười . lên không nghe rõ lời...,0,dev
...,...,...,...,...
46002,46002,"trong trường hợp này, theo ls. khanh, bà hằng...",1,test
46003,46003,bà cũng không ít lần chỉ trích nặng nề những ...,0,test
46004,46004,“bà nguyễn phương hằng có nhiều biểu hiện đã ...,0,test
46005,46005,vũ đức khanh nói. bà nguyễn phương hằng bắt đ...,0,test
46006,46006,".. trước khi bị bắt, bà nguyễn phương hằng đã ...",0,test

In [66]:
data2 = pd.concat([data2, test_data])

In [67]:
data1.to_csv('origin/data1_dedup.csv', index=False)

In [68]:
data2.to_csv('origin/data2_dedup.csv', index=False)