In [23]:
import pandas as pd

In [24]:
origin_df = pd.read_csv('Iterations\\Iter1\\data2_dedup.csv')

In [25]:
update_df = pd.read_csv('Iterations\\Iter1\\1.1\\finish_data2.csv')

In [26]:
origin_df

,id,text,label,dataset_type
0,1,Ch·∫Øc c≈©ng bi·∫øt ko t·ªìn t·∫°i ƒëc bao l√¢u n·ªØa n√™n c...,1,train
1,9,Emma Nguyen v·∫≠y m√† ca ng·ª£i b√™n kia l·∫Øm... V·ªÅ l...,1,train
2,11,Nhung Pham Ai ch√™ ngh√®o ngta c√≥ ti·ªÅn ƒëi n∆∞·ªõc n...,1,train
3,13,·ª¶a b√™ ƒë√™ c√≥ lol h·∫£ ta ??üòÇüòÇüòÇ,1,train
4,16,L√†m th√™m ch·ª•c c·ªß m·ªü h√≤m csgo anh √™i :V,0,train
...,...,...,...,...
22999,46002,"trong tr∆∞·ªùng h·ª£p n√†y, theo ls. khanh, b√† h·∫±ng...",1,test
23000,46003,b√† c≈©ng kh√¥ng √≠t l·∫ßn ch·ªâ tr√≠ch n·∫∑ng n·ªÅ nh·ªØng ...,0,test
23001,46004,‚Äúb√† nguy·ªÖn ph∆∞∆°ng h·∫±ng c√≥ nhi·ªÅu bi·ªÉu hi·ªán ƒë√£ ...,0,test
23002,46005,v≈© ƒë·ª©c khanh n√≥i. b√† nguy·ªÖn ph∆∞∆°ng h·∫±ng b·∫Øt ƒë...,0,test
23003,46006,".. tr∆∞·ªõc khi b·ªã b·∫Øt, b√† nguy·ªÖn ph∆∞∆°ng h·∫±ng ƒë√£ ...",0,test

In [27]:
update_df

,id,text,label,dataset_type,predict_label,gemini_label,different,true_label
0,702,"g·ªçi l√† ƒë·ªï th·ª´a, l·∫°i l√† chuy·ªán h√†i nh√† s·∫£n",1,train,0,0,True,1
1,729,Ti·ªÅn ƒë√¢u mua th·∫ßy ∆°i √°o ƒë·∫Øt v√£i ƒë√°i,1,train,0,0,True,1
2,842,Tu√¢n Anh Trinh thua thua,0,train,1,1,True,0
3,866,C√≥ n√£o m√† ƒë·ªÉ tay nhanh h∆°n n√£o :v,0,train,1,1,True,1
4,1396,M√¨nh ƒëang t√¨m m·ªôt con b√≤ ƒë·∫∑c ƒëi·ªÉm nh·∫≠n d·∫°ng n√≥...,1,train,0,0,True,1
...,...,...,...,...,...,...,...,...
5168,66998,"ng∆∞·ªùi ƒë·ª©c, ng∆∞·ªùi nh·∫≠t, ng∆∞·ªùi do th√°i, ng∆∞·ªùi c...",0,dev,1,0,False,0
5169,67023,ph·∫£i c·ªë l√†m c√¥ng vi·ªác c·ªßa m·ªôt ƒë·ª©a con g∆∞∆°ng m...,0,dev,1,0,False,0
5170,67027,"ƒë√™m nay, ƒë√£ qu√° gi·ªù ƒëi ng·ªß b√¨nh th∆∞·ªùng, t√¥i b...",0,dev,1,0,False,0
5171,67037,"ng√†y 7/3/2019, t·ªï ch·ª©c ph√≥ng vi√™n kh√¥ng bi√™n ...",0,dev,1,0,False,0
5172,67133,g√≥c c·∫£nh b√°o: l√†m gi·∫£ l·ªánh b·∫Øt t·∫°m giam ƒë·ªÉ l·ª´a...,0,dev,1,0,False,0

In [28]:
## Update the label of df2 to true label
for i in range(0, len(update_df)):
    origin_df.loc[origin_df['text'] == update_df['text'][i], 'update_label'] = update_df['true_label'][i]
    origin_df.loc[origin_df['text'] == update_df['text'][i], 'check'] = True

In [29]:
origin_df

,id,text,label,dataset_type,update_label,check
0,1,Ch·∫Øc c≈©ng bi·∫øt ko t·ªìn t·∫°i ƒëc bao l√¢u n·ªØa n√™n c...,1,train,NaN,NaN
1,9,Emma Nguyen v·∫≠y m√† ca ng·ª£i b√™n kia l·∫Øm... V·ªÅ l...,1,train,NaN,NaN
2,11,Nhung Pham Ai ch√™ ngh√®o ngta c√≥ ti·ªÅn ƒëi n∆∞·ªõc n...,1,train,NaN,NaN
3,13,·ª¶a b√™ ƒë√™ c√≥ lol h·∫£ ta ??üòÇüòÇüòÇ,1,train,NaN,NaN
4,16,L√†m th√™m ch·ª•c c·ªß m·ªü h√≤m csgo anh √™i :V,0,train,NaN,NaN
...,...,...,...,...,...,...
22999,46002,"trong tr∆∞·ªùng h·ª£p n√†y, theo ls. khanh, b√† h·∫±ng...",1,test,1.0,True
23000,46003,b√† c≈©ng kh√¥ng √≠t l·∫ßn ch·ªâ tr√≠ch n·∫∑ng n·ªÅ nh·ªØng ...,0,test,NaN,NaN
23001,46004,‚Äúb√† nguy·ªÖn ph∆∞∆°ng h·∫±ng c√≥ nhi·ªÅu bi·ªÉu hi·ªán ƒë√£ ...,0,test,NaN,NaN
23002,46005,v≈© ƒë·ª©c khanh n√≥i. b√† nguy·ªÖn ph∆∞∆°ng h·∫±ng b·∫Øt ƒë...,0,test,NaN,NaN
23003,46006,".. tr∆∞·ªõc khi b·ªã b·∫Øt, b√† nguy·ªÖn ph∆∞∆°ng h·∫±ng ƒë√£ ...",0,test,NaN,NaN

In [32]:
origin_df.loc[origin_df['check'] == True]

,id,text,label,dataset_type,update_label,check
12,53,Gi√°o √°n v·ªÅ One champ Lee b√∫ ƒë√° v√† r·ª•ng m·∫•t x√°c,1,train,1.0,True
130,386,Cho c·ª•c g·∫°ch v√†o c√°i k√≠nh,0,train,1.0,True
194,599,"g·ªçi l√† ƒë·ªï th·ª´a, l·∫°i l√† chuy·ªán h√†i nh√† s·∫£n",1,train,1.0,True
220,685,H·ªça t·ª´ mi·ªáng m√† ra,1,train,1.0,True
239,737,C√≥ n√£o m√† ƒë·ªÉ tay nhanh h∆°n n√£o :v,1,train,1.0,True
...,...,...,...,...,...,...
22994,45997,v·ª• b·∫Øt nguy·ªÖn ph∆∞∆°ng h·∫±ng: lu·∫≠t s∆∞ c·∫£nh b√°o v·ªÅ...,1,test,1.0,True
22996,45999,"ngo√†i nh·ªØng ng∆∞·ªùi h√¢m m·ªô, ƒëa s·ªë c√¥ng lu·∫≠n vi·ªá...",1,test,1.0,True
22997,46000,√¥ng n√≥i ƒë√¢y l√† ƒëi·ªÅu kho·∫£n an ninh nh·∫±m ‚Äúh√¨nh ...,1,test,1.0,True
22998,46001,"v√¨ v·∫≠y, theo √¥ng, n·∫øu kh√¥ng c·∫©n th·∫≠n suy x√©t ...",1,test,1.0,True
22999,46002,"trong tr∆∞·ªùng h·ª£p n√†y, theo ls. khanh, b√† h·∫±ng...",1,test,1.0,True

In [19]:
origin_df.loc[origin_df['check'].notna()]

,id,text,label,dataset_type,check
7,32375,T√¥i kh√¥ng hi·ªÉu sao l·∫°i ƒë·ªÉ v·∫≠y.,0,train,True
22,5553,Kh√¥ng bi·∫øt t·ªët x·∫•u! Ch·∫•t ph√°t nh∆∞ n√†o nh∆∞ng ng...,1,train,True
29,7102,con naÃÄy th∆∞Ã£c s∆∞Ã£ noÃÅ gi√¥ÃÅng nh∆∞ con thuÃÅ nh√¥...,1,train,True
36,43278,chuy·ªán ƒë·ªùi c·ªông s·∫£n l∆∞u vong (7) ***** 21) m∆∞·ªù...,1,train,True
48,6289,C√°i qu·∫ßn in h·ªát c√°i √Ω th·ª©c,1,train,True
...,...,...,...,...,...
22965,42839,B·ªò C√îNG AN TUY·ªÇN H∆†N 16.000 L√çNH CSCƒê NƒÉm 2024...,0,train,True
22980,40625,v·∫≠y ƒëi·ªÅu 331 b·ªô lu·∫≠t h√¨nh s·ª± 2015 c√≥ n·ªôi dung...,0,train,True
22981,37954,khu k√Ω t√∫c x√° n·∫±m g·∫ßn v·ªõi b·ªánh vi·ªán ƒëa khoa t...,0,train,True
22983,3196,"T√∫ Trinh ko ch·∫°y ƒÉn c·ª©t, ƒÉn ƒëb √† üôÑ",1,train,True
22994,38935,42.000 ‚Äúb·ªã h·∫°‚Äù c·ªßa ch∆∞∆°ng tr√¨nh vua tin v·ªãt! m...,0,train,True

In [33]:
origin_df.sort_values(by='id', inplace=True)

In [34]:
origin_df

,id,text,label,dataset_type,update_label,check
0,1,Ch·∫Øc c≈©ng bi·∫øt ko t·ªìn t·∫°i ƒëc bao l√¢u n·ªØa n√™n c...,1,train,NaN,NaN
1,9,Emma Nguyen v·∫≠y m√† ca ng·ª£i b√™n kia l·∫Øm... V·ªÅ l...,1,train,NaN,NaN
2,11,Nhung Pham Ai ch√™ ngh√®o ngta c√≥ ti·ªÅn ƒëi n∆∞·ªõc n...,1,train,NaN,NaN
3,13,·ª¶a b√™ ƒë√™ c√≥ lol h·∫£ ta ??üòÇüòÇüòÇ,1,train,NaN,NaN
4,16,L√†m th√™m ch·ª•c c·ªß m·ªü h√≤m csgo anh √™i :V,0,train,NaN,NaN
...,...,...,...,...,...,...
22999,46002,"trong tr∆∞·ªùng h·ª£p n√†y, theo ls. khanh, b√† h·∫±ng...",1,test,1.0,True
23000,46003,b√† c≈©ng kh√¥ng √≠t l·∫ßn ch·ªâ tr√≠ch n·∫∑ng n·ªÅ nh·ªØng ...,0,test,NaN,NaN
23001,46004,‚Äúb√† nguy·ªÖn ph∆∞∆°ng h·∫±ng c√≥ nhi·ªÅu bi·ªÉu hi·ªán ƒë√£ ...,0,test,NaN,NaN
23002,46005,v≈© ƒë·ª©c khanh n√≥i. b√† nguy·ªÖn ph∆∞∆°ng h·∫±ng b·∫Øt ƒë...,0,test,NaN,NaN
23003,46006,".. tr∆∞·ªõc khi b·ªã b·∫Øt, b√† nguy·ªÖn ph∆∞∆°ng h·∫±ng ƒë√£ ...",0,test,NaN,NaN

In [35]:
origin_df.drop(columns=['update_label'], inplace=True)

In [36]:
origin_df.to_csv('Iterations\\Iter1\\data2_done.csv', index=False)